site :opscode

metadata
cookbook 'simple_iptables', git: 'https://github.com/rtkwlf/cookbook-simple-iptables.git', tag: '0.6.4'
cookbook 'python', git: 'https://github.com/poise/python.git', branch: 'master'
